<?php
// $Id$

/**
 * MediaMosa is a Full Featured, Webservice Oriented Media Management and
 * Distribution platform (http://www.vpcore.nl)
 *
 * Copyright (C) 2009 SURFnet BV (http://www.surfnet.nl) and Kennisnet
 * (http://www.kennisnet.nl)
 *
 * MediaMosa is based on the open source Drupal platform and
 * was originally developed by Madcap BV (http://www.madcap.nl)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, you can find it at:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */

 /**
  * @file
  * The mediamosa status module.
  */

// Permissions.
define('MEDIAMOSA_PERM_VIEW_STATUS', mediamosa_settings::MEDIAMOSA_PERM_VIEW . ' status');

/**
 * Implementation of hook_menu().
 */
function mediamosa_maintenance_status_menu() {
  $items = array();

  $items['admin/mediamosa/status'] = array(
    'title' => 'MediaMosa status page',
    'page callback' => '_mediamosa_maintenance_status',
    'type' => MENU_CALLBACK,
    'access arguments' => array(MEDIAMOSA_PERM_VIEW_STATUS),
  );

  return $items;
}

/**
 * Trigger status page.
 */
function mediamosa_maintenance_status_cron() {
  // Just trigger, it has his own protection on overrun.
 // mediamosa_http::do_head_call('http://localhost/');
}

/**
 * Implements hook_mediamosa_register_rest_call().
 */
function mediamosa_maintenance_status_mediamosa_register_rest_call() {

  $a_rest_calls = array();

  $a_rest_calls['execute_default_tests'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_list',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Retrieve the listing of the current registered MediaMosa REST calls.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_2_0_0,
    mediamosa_rest_call::ACCESS => mediamosa_rest_call::ACCESS_INTERNAL_ONLY,
  );

  return $a_rest_calls;
}



function _mediamosa_maintenance_status() {

}
