<?php
// $Id$

/**
 * MediaMosa is a Full Featured, Webservice Oriented Media Management and
 * Distribution platform (http://www.vpcore.nl)
 *
 * Copyright (C) 2009 SURFnet BV (http://www.surfnet.nl) and Kennisnet
 * (http://www.kennisnet.nl)
 *
 * MediaMosa is based on the open source Drupal platform and
 * was originally developed by Madcap BV (http://www.madcap.nl)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, you can find it at:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */

/**
 * @file
 * The Application module.
 */

/**
 * Implements hook_mediamosa_register_rest_call().
 */
function mediamosa_app_mediamosa_register_rest_call() {
  $a_rest_calls = array();

  // Asset search.
  $a_rest_calls['preview_profile_id'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_app_get_default_transcode_profile',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Get the preview profile ID.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_app',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_7,
  );

  return $a_rest_calls;
}

/**
 * Implement hook_menu().
 */
function mediamosa_app_menu() {
  $items = array();

  $items['admin/mediamosa/config/app'] = array(
    'title' => 'Client applications',
    'description' => 'List all MediaMosa End User Applications.',
    'page callback' => '_mediamosa_app_list',
    'access arguments' => array('access mediamosa'),
  );

  $items['admin/mediamosa/config/app/%/contacts'] = array(
    'title' => 'Client application contacts',
    'type' => MENU_CALLBACK,
    'page callback' => '_mediamosa_app_contacts',
    'page arguments' => array(1),
    'access arguments' => array('administer mediamosa config app'),
  );

  return $items;
}

/**
 * Implement hook_permission().
 */
function mediamosa_app_permission() {
  return array(
    'administer mediamosa config app' =>  array(
      'title' => t('Adminster MediaMosa applications.'),
      'description' => t('Give administer rights for editing MediaMosa 2 applications.'),
    ),
  );
}

/**
 * Show a listing of apps.
 */
function _mediamosa_app_list() {

  // Our header defenition
  $header = array(t('Application ID'), t('Name'), t('Quota'), t('Offline webservices'), t('Owner'), t('Active'), t('Contacts'));

  $result = mediamosa_db::db_select(mediamosa_app_db::TABLE_NAME, 'a')->extend('PagerDefault')//->extend('TableSort');
    ->fields('a')
    ->limit(10)
    ->execute();

  $rows = array();
  foreach ($result as $row) {
    $rows[] = array(
      $row[mediamosa_app_db::APP_ID],
      $row[mediamosa_app_db::NAME],
      $row[mediamosa_app_db::QUOTA],
      '', // @TODO: offline webservices
      $row[mediamosa_app_db::OWNER],
      $row[mediamosa_app_db::ACTIVE],
      l(t('View'), 'admin/mediamosa/app/'. $row[mediamosa_app_db::APP_ID] . '/contacts'),
    );
  }

  $output = theme('table', $header, $rows);
  $output .= theme('pager');

  return $output;
}

/**
 * Show more specific information about a application.
 *
 * @param integer $app_id
 */
function _mediamosa_app_contacts($app_id) {
  $response = t('Technical and administrative contact for a client application.');

  $query = mediamosa_db::db_select(mediamosa_app_db::TABLE_NAME, 'a')->extend('PagerDefault');
  $result = $query
    ->fields('a')
    ->condition('a.app_id', $app_id)
    ->limit(10)
    ->execute();

  $rows = array();
  foreach ($result as $row) {
    $rows[] = array(
      $row[mediamosa_app_db::APP_ID],
      $row[mediamosa_app_db::TECHNICAL_NAME],
      $row[mediamosa_app_db::TECHNICAL_PHONE],
      $row[mediamosa_app_db::TECHNICAL_EMAIL],
      t('Technical'),
    );
    $rows[] = array(
      $row[mediamosa_app_db::APP_ID],
      $row[mediamosa_app_db::ADMINISTRATIVE_NAME],
      $row[mediamosa_app_db::ADMINISTRATIVE_PHONE],
      $row[mediamosa_app_db::ADMINISTRATIVE_EMAIL],
      t('Administrative'),
    );
  }

  $output = theme('table', array(t('Application ID'), t('Name'), t('Phone'), t('E-mail'), t('Type')), $rows);
  //$output .= l(t('Return to MediaMosa 2 Application Listing'), 'admin/mediamosa/app');
  $output .= theme('pager');

  return $output;
}
