<?php
// $Id$

/**
 * MediaMosa is Open Source Software to build a Full Featured, Webservice Oriented Media Management and
 * Distribution platform (http://mediamosa.org)
 *
 * Copyright (C) 2009 SURFnet BV (http://www.surfnet.nl) and Kennisnet
 * (http://www.kennisnet.nl)
 *
 * MediaMosa is based on the open source Drupal platform and
 * was originally developed by Madcap BV (http://www.madcap.nl)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, you can find it at:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */

 /**
  * @file
  */

// SESSIONs.
define('MEDIAMOSA_MAINTENACE_BROWSE_ASSETS_SESSION', 'mediamosa_maintenance_browse_assets_session');
define('MEDIAMOSA_MAINTENACE_BROWSE_COLLECTIONS_SESSION', 'mediamosa_maintenance_browse_collections_session');

// Include my files.
module_load_include('inc', 'mediamosa_maintenance_browse', 'mediamosa_maintenance_browse');
module_load_include('inc', 'mediamosa_maintenance_browse', 'mediamosa_maintenance_browse_asset');
module_load_include('inc', 'mediamosa_maintenance_browse', 'mediamosa_maintenance_browse_collection');
module_load_include('inc', 'mediamosa_maintenance_browse', 'mediamosa_maintenance_browse_restcalls');

/**
 * Implement hook_permission().
 */
function mediamosa_maintenance_browse_permission() {
  return array(
    'access mediamosa assets' =>  array(
      'title' => t('Browse assets'),
      'description' => t('Users with this permission may browse through the assets.'),
    ),
    'access mediamosa collections' =>  array(
      'title' => t('Browse collections'),
      'description' => t('Users with this permission may browse through the collections.'),
    ),
  );
}

/**
 * Implementation of hook_menu().
 */
function mediamosa_maintenance_browse_menu() {
  $items = array();

  $items['admin/mediamosa/browse/asset'] = array(
    'title' => 'Asset browser',
    'description' => 'View assets currently in our database.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mediamosa_maintenance_browse_asset_form'),
    'access arguments' => array('access mediamosa assets'),
  );

  $items['admin/mediamosa/browse/collection'] = array(
    'title' => 'Collection browser',
    'description' => 'View collections currently in our database.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mediamosa_maintenance_browse_collection_form'),
    'access arguments' => array('access mediamosa collections'),
  );

  $items['admin/mediamosa/browse/asset/%'] = array(
    'title' => 'Asset details',
    'type' => MENU_CALLBACK,
    'page callback' => 'mediamosa_maintenance_browse_asset_details',
    'page arguments' => array(4),
    'access arguments' => array('access mediamosa assets'),
  );

  $items['admin/mediamosa/browse/restcall'] = array(
    'title' => 'Rest calls browser',
    'description' => 'View and browse through the REST calls of MediaMosa.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mediamosa_maintenance_browse_restcall_form'),
    'access arguments' => array('access mediamosa restcalls'),
  );

  $items['admin/mediamosa/browse/restcall/%/%'] = array(
    'title' => 'Detail rest calls',
    'description' => 'View the details of a REST call.',
    'page callback' => 'mediamosa_maintenance_browse_restcall_details',
    'page arguments' => array(4, 5),
    'access arguments' => array('access mediamosa restcalls'),
  );

  return $items;
}
