<?php
// $Id$

/**
 * MediaMosa is Open Source Software to build a Full Featured, Webservice Oriented Media Management and
 * Distribution platform (http://mediamosa.org)
 *
 * Copyright (C) 2011 SURFnet BV (http://www.surfnet.nl) and Kennisnet
 * (http://www.kennisnet.nl)
 *
 * MediaMosa is based on the open source Drupal platform and
 * was originally developed by Madcap BV (http://www.madcap.nl)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, you can find it at:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */

/**
 * @file
 * PDF tool module.
 */

// Constants.
/**
 * Mime type: application/pdf
 */
define('MEDIAMOSA_TOOL_PDF_MIME_TYPE_PDF', 'application/pdf');

/**
 * Short id of the module.
 */
define('MEDIAMOSA_TOOL_PDF_ID', 'pdf');

/**
 * Key value separator.
 */
define('MEDIAMOSA_TOOL_PDF_KEY_VALUE_SEPARATOR', ':');

/**
 * Helper function to recognize mime type as transcode.
 */
function mediamosa_tool_pdf_is_recognized_as_transcode($mime_type) {
  $is_found = FALSE;

  switch ($mime_type) {
    case MEDIAMOSA_TOOL_PDF_MIME_TYPE_PDF:
      $is_found = TRUE;
      break;
  }

  return $is_found;
}

/**
 * Implements hook_mediamosa_tool_is_recognized_as_transcode().
 */
function mediamosa_tool_pdf_mediamosa_tool_is_recognized_as_transcode($mime_type) {
  $is_found = mediamosa_tool_pdf_is_recognized_as_transcode($mime_type);
  return $is_found;
}

/**
 * Implements hook_mediamosa_tool_transcode().
 */
function mediamosa_tool_pdf_mediamosa_tool_transcode($mime_type) {
  $is_found = mediamosa_tool_pdf_is_recognized_as_transcode($mime_type);
  return ($is_found ? '/internal/job/$job_id/exec/pdf' : FALSE);
}

/**
 * Helper function to recognize mime type as analyse.
 */
function mediamosa_tool_pdf_is_recognized_as_analyse($mime_type) {
  $is_found = FALSE;

  switch ($mime_type) {
    case MEDIAMOSA_TOOL_PDF_MIME_TYPE_PDF:
      $is_found = TRUE;
      break;
  }

  return $is_found;
}

/**
 * Implements hook_mediamosa_tool_is_recognized_as_analyse().
 */
function mediamosa_tool_pdf_mediamosa_tool_is_recognized_as_analyse($mime_type) {
  $is_found = mediamosa_tool_pdf_is_recognized_as_analyse($mime_type);
  return $is_found;
}

/**
 * Implements hook_mediamosa_tool_analyse().
 *
 * @param array $job_ext
 */
function mediamosa_tool_pdf_mediamosa_tool_analyse($job_ext) {
  $command_type = 'mediamosa_tool_pdf';

  $mapping_array = array();
  $type_array = array();
  foreach (mediamosa_tool_mapping::get(MEDIAMOSA_TOOL_PDF_ID) as $record) {
    $property = mediamosa_asset_metadata_property::property_get_row($record[mediamosa_tool_mapping_db::PROP_ID]);

    $mapping_array[$record[mediamosa_tool_mapping_db::PARAMETER]] = $property[mediamosa_asset_metadata_property_db::NAME];
    $type_array[$record[mediamosa_tool_mapping_db::PARAMETER]] = $property[mediamosa_asset_metadata_property_db::TYPE];
  }

  $app_id = $job_ext[mediamosa_job_db::APP_ID];
  $app = mediamosa_app::get_by_appid($app_id);
  $job_id = $job_ext[mediamosa_job_db::ID];
  $mediafile_id = $job_ext[mediamosa_job_db::MEDIAFILE_ID];
  $mediafile = mediamosa_asset_mediafile::get($mediafile_id);
  $asset_id = $mediafile[mediamosa_asset_mediafile_db::ASSET_ID];

  // Execute.
  $execution_string = strtr('pdfinfo @mediafile_location', array(
    '@mediafile_location' => mediamosa_configuration_storage::mediafile_filename_get($mediafile),
  ));
  $output_array = array();
  $output_string = mediamosa_io::exec($execution_string, $output_array);
  $link_asset = mediamosa_job_server::get_asset_link($job_id);
  mediamosa_watchdog::log_mediafile($mediafile_id, 'Command for @command_type: @command ; returned output: @s_output - @a_output<br /><br />@link',
    array(
      '@command_type' => $command_type,
      '@command' => $execution_string,
      '@s_output' => $output_string,
      '@a_output' => print_r($output_array, TRUE),
      '@link' => $link_asset,
    )
  );

  // Parse.
  $parse_array = array();
  // Get full definitions.
  $metadata_definitions_full = mediamosa_asset_metadata_property::get_metadata_properties_full($app_id);
  // append, replace, update
  $action = 'update';
  foreach ($output_array as $output_line) {
    if (strpos($output_line, MEDIAMOSA_TOOL_PDF_KEY_VALUE_SEPARATOR) !== FALSE) {
      // Eg. CreationDate:   Wed Jul  8 16:14:29 2009
      // => array('CreationDate', 'Wed Jul  8 16:14:29 2009')
      list($key, $metadata_value) = explode(MEDIAMOSA_TOOL_PDF_KEY_VALUE_SEPARATOR, $output_line, 2);
      $key = drupal_strtolower(trim($key));
      $metadata_value = trim($metadata_value);

      if ($metadata_value && isset($mapping_array[$key]) && $mapping_array[$key]) {
        // Datetime conversion.
        if ($type_array[$key] == mediamosa_asset_metadata_property_db::TYPE_DATETIME) {
          $metadata_value = mediamosa_datetime::time_string2utc_date($metadata_value, $app[mediamosa_app_db::TIMEZONE]);
        }

        $parse_array[$mapping_array[$key]] = array($metadata_value);
      }
    }
  }
  mediamosa_asset_metadata::metadata_create($asset_id, $metadata_definitions_full, $parse_array, $action);
}

/**
 * Implements hook_mediamosa_tool_analyse_options().
 */
function mediamosa_tool_pdf_mediamosa_tool_analyse_options() {
  return array(
    'name' => t('PDF'),
    'description' => t('PDF files'),
    'value' => MEDIAMOSA_TOOL_PDF_ID,
  );
}

/**
 * Get module id.
 * Implements hook_mediamosa_tool_iteration().
 */
function mediamosa_tool_pdf_mediamosa_tool_iteration() {
  return MEDIAMOSA_TOOL_PDF_ID;
}

/**
 * Implements hook_mediamosa_register_rest_call().
 */
function mediamosa_tool_pdf_mediamosa_register_rest_call() {

  $rest_calls = array();

  $rest_calls['job/$job_id/exec/pdf'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_job_exec_pdf',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_tool_pdf',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_2_3_0,
    mediamosa_rest_call::ACCESS => mediamosa_rest_call::ACCESS_INTERNAL_ONLY,
    mediamosa_rest_call::NO_USER_ABORT => TRUE,
  );

  return $rest_calls;
}

/**
 * Implements hook_mediamosa_register_rest_call_doc().
 */
function mediamosa_tool_pdf_mediamosa_register_rest_call_doc() {

  $rest_calls = array();

  $rest_calls['job/$job_id/exec/pdf'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::TITLE => 'Start transcoding PDF.',
    mediamosa_rest_call::DESCRIPTION => 'Start transcoding PDF.',
    mediamosa_rest_call::EXAMPLE_REQUEST => '',
    mediamosa_rest_call::RESPONSE_FIELDS => array(),
    mediamosa_rest_call::EXAMPLE_RESPONSE => '',
  );

  return $rest_calls;
}
