<?php
// $Id$

/**
 * MediaMosa is Open Source Software to build a Full Featured, Webservice
 * Oriented Media Management and Distribution platform (http://mediamosa.org)
 *
 * Copyright (C) 2010 SURFnet BV (http://www.surfnet.nl) and Kennisnet
 * (http://www.kennisnet.nl)
 *
 * MediaMosa is based on the open source Drupal platform and
 * was originally developed by Madcap BV (http://www.madcap.nl)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, you can find it at:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */

 /**
  * @file
  * Mediamosa tool.
  */

function mediamosa_tool_mediamosa_register_rest_call_doc() {
  $a_rest_calls = array();

  $a_rest_calls['transcode/parameter'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::TITLE => 'Get transcode parameters.',
    mediamosa_rest_call::DESCRIPTION => 'Get transcode parameters.',
    mediamosa_rest_call::EXAMPLE_REQUEST => 'transcode/parameter',
    mediamosa_rest_call::RESPONSE_FIELDS => array(),
    mediamosa_rest_call::EXAMPLE_RESPONSE => '<items>
  <item id="1">
    <transcode_mapping_id>1</transcode_mapping_id>
    <tool>ffmpeg</tool>
    <nice_parameter>videobitrate</nice_parameter>
    <tool_parameter>-b</tool_parameter>
    <min_value>128000</min_value>
    <max_value>800000</max_value>
    <allowed_value></allowed_value>
    <default_value>200000</default_value>
    <required>FALSE</required>
    <created>2010-04-07 12:39:03</created>
    <changed>2010-04-07 12:39:03</changed>
  </item>
</items>',
  );

  return $a_rest_calls;
}

/**
 * Implements hook_mediamosa_register_rest_call().
 */
function mediamosa_tool_mediamosa_register_rest_call() {
  $a_rest_calls = array();

  // Get transcode parameters.
  $a_rest_calls['transcode/parameter'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_tool_params_search',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_tool_params',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_7_0,
  );

  return $a_rest_calls;
}
