<?php
// $Id$

/**
 * MediaMosa is a Full Featured, Webservice Oriented Media Management and
 * Distribution platform (http://www.vpcore.nl)
 *
 * Copyright (C) 2009 SURFnet BV (http://www.surfnet.nl) and Kennisnet
 * (http://www.kennisnet.nl)
 *
 * MediaMosa is based on the open source Drupal platform and
 * was originally developed by Madcap BV (http://www.madcap.nl)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, you can find it at:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */

 /**
  * @file
  * The maintenance module.
  */

/**
 * Implements hook_permission()
 */
function mediamosa_configuration_permission() {
  return array(
    'administer mediamosa configuration' => array(
      'title' => t('MediaMosa Configuration administer permissions'),
      'description' => t('Manage the whole configuration of MediaMosa to be edited by an MediaMosa right.')
    )
  );
}

/**
 * Implement hook_menu().
 */
function mediamosa_configuration_menu() {
  $items = array();

  // Configuration.
  $items['admin/config/mediamosa'] = array(
    'title' => 'MediaMosa',
    'description' => 'MediaMosa Configuration.',
    'position' => 'left',
    'weight' => 10,
    'page callback' => 'mediamosa_configuration_menu_block_page',
    'access arguments' => array('administer mediamosa configuration'),
    //'file' => '/modules/system/system.admin.inc',
  );

  $items['admin/config/mediamosa/configuration'] = array(
    'title' => 'Configuration',
    'description' => 'The configuration of MediaMosa settings. You might have to enable maintenance modules for more options.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mediamosa_configuration'),
    'access arguments' => array('administer mediamosa configuration'),
  );

  return $items;
}

/**
 * Block code copied from drupal system.inc.
 *
 * @return
 *   The output HTML.
 */
function mediamosa_configuration_menu_block_page() {
  $item = menu_get_item();
  $content = system_admin_menu_block($item);

  if ($content) {
    $output = theme('admin_block_content', $content);
  }
  else {
    $output = t('You do not have any administrative items.');
  }

  return $output;
}

/**
 * Our Maintenance settings form.
 *
 * @return array
 */
function mediamosa_configuration() {

  // Build the settings form and enrich it with our settings collect hook.
  return system_settings_form(module_invoke_all('mediamosa_configuration_collect'), FALSE);
}

/**
 * Implements hook_submit.
 *
 * @param array $form
 * @param array $form_state
 */
function mediamosa_configuration_submit($form, $form_state) {

  // Now call our submit hooks.
  module_invoke_all('mediamosa_configuration_submit', $form, $form_state);
}
