<?php
// $Id$

/**
 * MediaMosa is a Full Featured, Webservice Oriented Media Management and
 * Distribution platform (http://www.vpcore.nl)
 *
 * Copyright (C) 2009 SURFnet BV (http://www.surfnet.nl) and Kennisnet
 * (http://www.kennisnet.nl)
 *
 * MediaMosa is based on the open source Drupal platform and
 * was originally developed by Madcap BV (http://www.madcap.nl)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, you can find it at:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */

/**
 * @file
 * SAN NAS module.
 */

/**
 * Implementation of hook_permissions()
 */
function mediamosa_maintenance_san_nas_permission() {
  return array('view mediamosa configuration sannas', 'administer mediamosa configuration sannas');
}

/**
 * Implementation of the hook_mediamosa_settings_collect()
 */
function mediamosa_maintenance_san_nas_mediamosa_configuration_collect() {
  $form['settings_sannas'] = array(
    '#type' => 'fieldset',
    '#title' => t('SAN NAS settings'),
    '#collapsible' => TRUE,
  );

  $form['settings_sannas']['mediamosa_current_mount_point'] = array(
    '#type' => 'textfield',
    '#title' => t('Linux mount point'),
    '#description' => t('Current Linux mount point.'),
    '#required' => TRUE,
    '#default_value' => mediamosa_san_nas::linux_get(),
  );

  $form['settings_sannas']['mediamosa_current_mount_point_windows'] = array(
    '#type' => 'textfield',
    '#title' => t('Windows mount point'),
    '#description' => t('Current Windows mount point (use UNC path).'),
    '#required' => TRUE,
    '#default_value' => mediamosa_san_nas::windows_get(),
  );

  return $form;
}

/**
 * Implementation of the hook_mediamosa_settings_submit()
 *
 * @param array $form
 * @param array $form_state
 */
function mediamosa_maintenance_san_nas_mediamosa_configuration_submit($form, $form_state) {
  assert(isset($form));
  assert(isset($form_state['values']['mediamosa_current_mount_point']));
  assert(isset($form_state['values']['mediamosa_current_mount_point_windows']));

  // Set the variables.
  mediamosa_san_nas::linux_set($form_state['values']['mediamosa_current_mount_point']);
  mediamosa_san_nas::linux_set($form_state['values']['mediamosa_current_mount_point_windows']);
}

/**
 * Implementation of hook_menu()
 *
function mediamosa_maintenance_san_nas_menu() {
  $items = array();

  $items['mediamosa/san_nas'] = array(
    'title' => t('MediaMosa SAN / NAS'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mediamosa_maintenance_san_nas_form'),
    'access arguments' => array('view mediamosa sannas'),
  );

  return $items;
}



/**
 * Implementation of hook_form()
 *
function mediamosa_maintenance_san_nas_form($node, $form_state) {
  assert($node);
  assert($form_state);

  $form = array();

  $a_san_nas = db_query(
    'SELECT current_mount_point, current_mount_point_windows FROM {san_nas_settings} LIMIT 1'
  )->fetchArray();

  $form['general'] = array(
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
    '#title' => t('VPX SAN/NAS mount points'),
    '#description' => t('Mount points on SAN/NAS.')
  );

  $form['general']['current_mount_point'] = array(
    '#type' => 'textfield',
    '#title' => t('Linux mount point'),
    '#description' => t('Current Linux mount point.'),
    '#required' => TRUE,
    '#default_value' => $a_san_nas['current_mount_point'],
  );

  $form['general']['current_mount_point_windows'] = array(
    '#type' => 'textfield',
    '#title' => t('Windows mount point'),
    '#description' => t('Current Windows mount point (use UNC path).'),
    '#required' => TRUE,
    '#default_value' => $a_san_nas['current_mount_point_windows'],
  );

  $form['submit'] = array('#type' => 'submit', '#value' => t('Save'));

  return $form;
}

/**
 * Implementation of hook_view()
 *
function mediamosa_maintenance_san_nas_view() {
  $content = t("MediaMosa SAN / NAS");
  return $content;
}

/**
 * Implementation of hook_submit()
 *
function mediamosa_maintenance_san_nas_form_submit(&$form_state, $form) {
  assert($form_state);

  if (!user_access('administer sannas')) {
    drupal_set_message('You have no "administer mediamosa sannas" rights.', 'error');
    return;
  }

  if ($form['values']['submit'] == t('Save')) {
    db_query(
      'UPDATE {san_nas_settings} SET current_mount_point = :current_mount_point, current_mount_point_windows = :current_mount_point_windows',
      array(
        ':current_mount_point' => $form['values']['current_mount_point'],
        ':current_mount_point_windows' => $form['values']['current_mount_point_windows'],
      )
    );
  }

  drupal_set_message(t("Mount points saved."));
}
*/