<?php
// $Id$

/**
 * MediaMosa is a Full Featured, Webservice Oriented Media Management and
 * Distribution platform (http://www.vpcore.nl)
 *
 * Copyright (C) 2009 SURFnet BV (http://www.surfnet.nl) and Kennisnet
 * (http://www.kennisnet.nl)
 *
 * MediaMosa is based on the open source Drupal platform and
 * was originally developed by Madcap BV (http://www.madcap.nl)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, you can find it at:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */

 /**
  * @file
  *
  */

/**
 * Implements hook_mediamosa_register_rest_call().
 */
function mediamosa_asset_mediamosa_register_rest_call() {
  $a_rest_calls = array();

  // Asset search.
  $a_rest_calls['asset'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_asset_search',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Search for assets based on input parameters and return a list of found assets.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_asset',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  // Change owner ship/group on asset/mediafile/collections. (1.x:  media_management_change_ownership)
  $a_rest_calls['change_ownership'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_change_ownership',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Change the ownership, app and/or group of assets, mediafiles and collections.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_asset',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  // Count number of asset based on owner/app/group (1.x:  media_management_asset_count)
  $a_rest_calls['asset/count'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_count_asset',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Return the number of asset based on app_id, owner_id and group_id.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_asset',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  // Get Asset Media Metadata (1.x:  media_management_metadata_definition_get)
  $a_rest_calls['metadata_tag'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_asset_metadata_property_list',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Retrieve the listing of the asset metadata definitions.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_asset_metadata_property',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_4_0,
  );

  // Create Asset Media Metadata. (1.x:  media_management_metadata_definition_create)
  $a_rest_calls['metadata_tag/create'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_asset_metadata_property_create',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Create a asset metadata definition.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_asset_metadata_property',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  // Delete Asset Media Metadata. (1.x:  media_management_metadata_definition_delete)
  $a_rest_calls['metadata_tag/delete'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_asset_metadata_property_delete',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Delete a asset metadata definition.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_asset_metadata_property',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  // Count number of mediafiles based on owner/app/group (1.x: media_management_mediafile_count)
  $a_rest_calls['mediafile/count'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_count_asset_mediafile',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Return the number of mediafile based on app_id, owner_id and group_id.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_asset_mediafile',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

    // Count number of mediafiles based on owner/app/group (1.x: media_management_mediafile_count)
  $a_rest_calls['mediafile/$mediafile_id'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_get_mediafile',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Return information about a mediafile.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_asset_mediafile',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

/*
 * Here for testing purpose.
  // Alias for metadata_tag.
  $a_rest_calls['asset/metadata/property'] = array(
    mediamosa_rest_call::ALIAS_FOR => 'metadata_tag',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_2_0_0,
  );
*/
  return $a_rest_calls;
}
