<?php
// $Id$

/**
 * MediaMosa is a Full Featured, Webservice Oriented Media Management and
 * Distribution platform (http://www.vpcore.nl)
 *
 * Copyright (C) 2009 SURFnet BV (http://www.surfnet.nl) and Kennisnet
 * (http://www.kennisnet.nl)
 *
 * MediaMosa is based on the open source Drupal platform and
 * was originally developed by Madcap BV (http://www.madcap.nl)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, you can find it at:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */

 /**
  * @file
  * The APP authentication module.
  */

/**
 * Implementation of hook_mediamosa_register_rest_call().
 */
function mediamosa_app_authentication_mediamosa_register_rest_call() {
  $a_rest_calls = array();

  $a_rest_calls['login'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_app_ident',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Log onto MediaMosa and authenticate as user end application.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_app_authentication',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
    mediamosa_rest_call::ACCESS => mediamosa_rest_call::ACCESS_FOR_EXTERNAL,
    mediamosa_rest_call::BEHAVE_AS_EXTERNAL => TRUE,
  );

  $a_rest_calls['login'][mediamosa_rest_call::METHOD_GET] = $a_rest_calls['login'][mediamosa_rest_call::METHOD_POST];


  $a_rest_calls['login/cookie'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_check_cookie',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Shows the contents of your cookie, for debugging purposes.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_app_authentication',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
    mediamosa_rest_call::ACCESS => mediamosa_rest_call::ACCESS_FOR_EXTERNAL,
    mediamosa_rest_call::BEHAVE_AS_EXTERNAL => TRUE,
  );

  return $a_rest_calls;
}

/**
 * Implementation of hook_mediamosa_mediamosa_app_authorized().
 */
function mediamosa_app_authentication_mediamosa_app_authorized() {
  // App already logged in?
  if (isset($_SESSION['mediamosa_app']) && isset($_SESSION['mediamosa_app']['app_id'])) {
    $_GET['app_id'] = $_SESSION['mediamosa_app']['app_id'];
    return TRUE;
  }

  // If IP white list is set, then we are 'simulated' authorized.
  $ip_address_whitelist = variable_get('mediamosa_debug_ip_whitelist', '');

  // Get the IP Address.
  $a_ip_address_whitelist = explode('|', $ip_address_whitelist);

  // If our IP address is in the white list, then we are 'authorized'.
  if (in_array($_SERVER['REMOTE_ADDR'], $a_ip_address_whitelist)) {
    return TRUE;
  }

  // Access denied.
  return FALSE;
}
