.\"                                      Hey, EMACS: -*- nroff -*-
.TH MEDIAMOSA SECTION "October 27, 2010"
.SH NAME
mediamosa \- program to moo.
.SH SYNOPSIS
.B mediamosa
.RI [ options ] " files" ...
.br
.B bar
.RI [ options ] " files" ...
.SH DESCRIPTION
This manual page documents briefly the
.B mediamosa
and
.B bar
commands.
.PP
\fBmediamosa\fP is a program that says moo.
.SH OPTIONS
These programs follow the usual GNU command line syntax, with long
options starting with two dashes (`-').
A summary of options is included below.
For a complete description, see the Info files.
.TP
.B \-h, \-\-help
Show summary of options.
.TP
.B \-v, \-\-version
Show version of program.
.SH SEE ALSO
.BR bar (1),
.BR baz (1).
.br
The programs are documented fully by
.IR "The Rise and Fall of Moo" ,
available via the Info system.
.SH AUTHOR
mediamosa was written by Madcap.
.PP
This manual page was written by Arjen Klop <a.klop@madcap.nl>,
for the Debian project (but may be used by others).
