<?php
// $Id$

/**
 * MediaMosa is Open Source Software to build a Full Featured, Webservice Oriented Media Management and
 * Distribution platform (http://mediamosa.org)
 *
 * Copyright (C) 2009 SURFnet BV (http://www.surfnet.nl) and Kennisnet
 * (http://www.kennisnet.nl)
 *
 * MediaMosa is based on the open source Drupal platform and
 * was originally developed by Madcap BV (http://www.madcap.nl)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, you can find it at:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */

/**
 * @file
 * Jobs module.
 */

/**
 * Trigger the server REST CRONs based on the server settings.
 *
 */
function mediamosa_job_cron() {

  $start = time();
  mediamosa_debug::log_debug('mediamosa_job_cron started.', array(), 'job_cron');

  // Get all enabled transcode servers (ON / CLOSE).
  $a_servers = mediamosa_server::get_enabled_transcode();
  $a_triggered = array();
  foreach ($a_servers as $a_server) {

    // Get URL.
    $url = mediamosa_http::uri2url($a_server[mediamosa_server_db::URI]) . '/internal/cron/jobserver';

    // Prevent multiple triggers if url is on more than one server.
    if (in_array($url, $a_triggered)) {
      continue;
    }

    // Mark triggered.
    $a_triggered[] = $url;

    // Log it.
    mediamosa_debug::log_debug('Triggering job server @ @uri', array('@uri' => $url));

    // Trigger.
    mediamosa_http::do_head_call_internal($url);
  }

  // Now trigger the jobschedular.
  $mediamosa_jobscheduler_uri = variable_get('mediamosa_jobscheduler_uri', NULL);

  if (isset($mediamosa_jobscheduler_uri)) {
    $url = mediamosa_http::uri2url($mediamosa_jobscheduler_uri) . '/internal/cron/jobscheduler';

    // Log it.
    mediamosa_debug::log_debug('Triggering job scheduler @ @uri', array('@uri' => $url));

    // Trigger.
    mediamosa_http::do_head_call_internal($url);
  }
  else {
    mediamosa::log('Jobschedular URL not set, please setup jobschedular server in the @link.', array('@link' => l('Mediamosa configuratiob', '/admin/mediamosa/config/global')), 'job_cron');
  }

  // Log it.
  mediamosa_debug::log_debug('mediamosa_job_cron ended: @secs', array('@sec' => time() - $start), 'job_cron');
}

/**
 * Implements hook_mediamosa_register_rest_call().
 */
function mediamosa_job_mediamosa_register_rest_call() {

  $a_rest_calls = array();

  $a_rest_calls['job/$job_id/status'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_job_set_status',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Change the status and other data of a job.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_job',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
    mediamosa_rest_call::ACCESS => mediamosa_rest_call::ACCESS_INTERNAL_ONLY,
  );

  $a_rest_calls['mediafile/$mediafile_id/analyse'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_job_analyse_mediafile',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Start an analyse job.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_job',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  $a_rest_calls['job/$job_id/progress'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_job_set_upload_progress',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Change the status and other data of a job.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_job',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
    mediamosa_rest_call::ACCESS => mediamosa_rest_call::ACCESS_INTERNAL_ONLY,
  );

  $a_rest_calls['job/create'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_job_create',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Create a job.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_job',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
    mediamosa_rest_call::ACCESS => mediamosa_rest_call::ACCESS_INTERNAL_ONLY,
  );

  $a_rest_calls['user/$user_id/joblist'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_job_user_search',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Return a listing of the given user ID as owner of the jobs.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_job',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  $a_rest_calls['asset/$asset_id/joblist'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_job_asset_search',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Return a listing of the given asset ID.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_job',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  $a_rest_calls['mediafile/$mediafile_id/joblist'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_job_mediafile_search',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Return a listing of the given mediafile ID.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_job',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  $a_rest_calls['job/$job_id/status'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_job_search',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Return a listing of the given job ID.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_job',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  $a_rest_calls['video/transcode/$job_id/status'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_job_search',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_DEPRECATED,
    mediamosa_rest_call::DESCRIPTION => 'Return a listing of the given job ID.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_job',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  $a_rest_calls['mediafile/transcode/$job_id/status'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_job_search',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Return a listing of the given job ID.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_job',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  $a_rest_calls['job/$job_id/transcode'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_job_create_transcode',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Create transcode job.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_job',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  $a_rest_calls['video/transcode/$job_id/transcode'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_job_create_transcode',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_DEPRECATED,
    mediamosa_rest_call::DESCRIPTION => 'Create transcode job.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_job',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  $a_rest_calls['mediafile/transcode/$job_id/transcode'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_job_create_transcode',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Create transcode job.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_job',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  $a_rest_calls['asset/$asset_id/still/create'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_job_create_still',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Create still job.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_job',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
  );

  $a_rest_calls['mediafile/$mediafile_id/still/create'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_job_create_still_for_mediafile',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Create still job for mediafile.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_job',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_7_0,
  );

  $a_rest_calls['job/create'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_job_create',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Create a job.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_job',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
    mediamosa_rest_call::ACCESS => mediamosa_rest_call::ACCESS_INTERNAL_ONLY,
  );

  $a_rest_calls['server/joblist'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_jobserver_job_search',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Retrieve the listing server jobs.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_job_server',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
    mediamosa_rest_call::ACCESS => mediamosa_rest_call::ACCESS_INTERNAL_ONLY,
  );

  $a_rest_calls['server/$job_id/delete'][mediamosa_rest_call::METHOD_POST] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_jobserver_job_delete',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Delete a server job.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_job_server',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_1_1_0,
    mediamosa_rest_call::ACCESS => mediamosa_rest_call::ACCESS_INTERNAL_ONLY,
  );

  $a_rest_calls['cron/jobscheduler'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_cron_jobscheduler',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Run the cron cycle for jobscheduler.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_job_scheduler',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_2_0_0,
    mediamosa_rest_call::ACCESS => mediamosa_rest_call::ACCESS_INTERNAL_ONLY,
  );

  $a_rest_calls['cron/jobserver'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_cron_jobserver',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Run the cron cycle for jobserver.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_job_server',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_2_0_0,
    mediamosa_rest_call::ACCESS => mediamosa_rest_call::ACCESS_INTERNAL_ONLY,
  );

  return $a_rest_calls;
}
