<?php
// $Id$

/**
 * MediaMosa is Open Source Software to build a Full Featured, Webservice
 * Oriented Media Management and Distribution platform (http://mediamosa.org)
 *
 * Copyright (C) 2010 SURFnet BV (http://www.surfnet.nl) and Kennisnet
 * (http://www.kennisnet.nl)
 *
 * MediaMosa is based on the open source Drupal platform and
 * was originally developed by Madcap BV (http://www.madcap.nl)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, you can find it at:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */

/**
 * @file
 * The status server module.
 */

/**
 * Implementation of hook_mediamosa_status_generate().
 */
function mediamosa_maintenance_status_server_mediamosa_status_generate() {
  $results = array();

  $results[] = array(
    'title' => t('Something'),
    'value' => t('OK'),
    //'description' => t('Some description...'),
    'severity' => MEDIAMOSA_MAINTENANCE_STATUS_RESULT_OK,
  );

  $statuses = array(
    'server' => array(
      'title' => t('Server monitoring'),
      'results' => $results,
    ),
  );

  variable_set('mediamosa_status_server', $statuses);
}

/**
 * Implementation of hook_mediamosa_status_collect().
 */
function mediamosa_maintenance_status_server_mediamosa_status_collect($reset = FALSE) {
  if ($reset) {
    mediamosa_maintenance_status_server_mediamosa_status_generate();
  }

  return variable_get('mediamosa_status_server', array());
}
