<?php
// $Id$

/**
 * MediaMosa is Open Source Software to build a Full Featured, Webservice
 * Oriented Media Management and Distribution platform (http://mediamosa.org)
 *
 * Copyright (C) 2010 SURFnet BV (http://www.surfnet.nl) and Kennisnet
 * (http://www.kennisnet.nl)
 *
 * MediaMosa is based on the open source Drupal platform and
 * was originally developed by Madcap BV (http://www.madcap.nl)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, you can find it at:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */

/**
 * @file
 * The status commponent module.
 */

/**
 * Constants.
 */

/**
 * Warning level for available in Mb.
 */
define('MEDIAMOSA_MAINTENANCE_STATUS_COMPONENT_SPACE_WARNING', 100);


/**
 * Implementation of hook_mediamosa_status_generate().
 *
 * @param with_variable boolean
 *   Use Drupal variables or not
 */
function mediamosa_maintenance_status_component_mediamosa_status_generate($with_variable = TRUE) {
  global $conf;

  $results = array();

  $mount_point = mediamosa_configuration_storage::mount_point_get();

  $results['mount_is_set'] = array(
    'title' => t('SANNAS'),
    'value' => t('Mount is set'),
    'severity' => _mediamosa_maintenance_status_okerror(!$mount_point),
  );

  $results['mount_is_exists'] = array(
    'title' => t('SANNAS'),
    'value' => t('Mount is exists'),
    'severity' => _mediamosa_maintenance_status_okerror(!mediamosa_io::is_dir($mount_point)),
  );

  // Structure check.
  $is_structured = TRUE;
  $is_writeable = TRUE;
  $is_structured = $is_structured && mediamosa_io::is_dir($mount_point . '/data');
  $is_writeable = $is_writeable && is_writable($mount_point . '/data');
  for ($i = 0; $i <= 9; $i++) {
    $is_structured = $is_structured && mediamosa_io::is_dir($mount_point . '/data/' . $i);
    $is_writeable = $is_writeable && is_writable($mount_point . '/data/' . $i);
  }
  for ($i = ord('a'); $i <= ord('z'); $i++) {
    $is_structured = $is_structured && mediamosa_io::is_dir($mount_point . '/data/' . chr($i));
    $is_writeable = $is_writeable && is_writable($mount_point . '/data/' . chr($i));
  }
  for ($i = ord('A'); $i <= ord('Z'); $i++) {
    $is_structured = $is_structured && mediamosa_io::is_dir($mount_point . '/data/' . chr($i));
    $is_writeable = $is_writeable && is_writable($mount_point . '/data/' . chr($i));
  }
  // data/stills.
  $is_structured = $is_structured && mediamosa_io::is_dir($mount_point . '/data/stills');
  $is_writeable = $is_writeable && is_writable($mount_point . '/data/stills');
  for ($i = 0; $i <= 9; $i++) {
    $is_structured = $is_structured && mediamosa_io::is_dir($mount_point . '/data/stills/' . $i);
    $is_writeable = $is_writeable && is_writable($mount_point . '/data/stills/' . $i);
  }
  for ($i = ord('a'); $i <= ord('z'); $i++) {
    $is_structured = $is_structured && mediamosa_io::is_dir($mount_point . '/data/stills/' . chr($i));
    $is_writeable = $is_writeable && is_writable($mount_point . '/data/stills/' . chr($i));
  }
  for ($i = ord('A'); $i <= ord('Z'); $i++) {
    $is_structured = $is_structured && mediamosa_io::is_dir($mount_point . '/data/stills/' . chr($i));
    $is_writeable = $is_writeable && is_writable($mount_point . '/data/stills/' . chr($i));
  }
  // Other.
  $is_structured = $is_structured && mediamosa_io::is_dir($mount_point . '/data/transcode');
  $is_writeable = $is_writeable && is_writable($mount_point . '/data/transcode');
  $is_structured = $is_structured && mediamosa_io::is_dir($mount_point . '/links');
  $is_writeable = $is_writeable && is_writable($mount_point . '/links');
  $is_structured = $is_structured && mediamosa_io::is_dir($mount_point . '/download_links');
  $is_writeable = $is_writeable && is_writable($mount_point . '/download_links');
  $is_structured = $is_structured && mediamosa_io::is_dir($mount_point . '/still_links');
  $is_writeable = $is_writeable && is_writable($mount_point . '/still_links');
  $is_structured = $is_structured && mediamosa_io::is_dir($mount_point . '/ftp');
  $is_writeable = $is_writeable && is_writable($mount_point . '/ftp');
  $results['mount_structure'] = array(
    'title' => t('SANNAS'),
    'value' => t('Mount has the good structure'),
    'severity' => _mediamosa_maintenance_status_okerror(!$is_structured),
  );
  $results['mount_writeable'] = array(
    'title' => t('SANNAS'),
    'value' => t('Mount structure is writeable'),
    'severity' => _mediamosa_maintenance_status_okerror(!$is_writeable),
  );


  $filename = $mount_point . '/data/transcode/test_' . mt_rand(0, 9999) . '.txt';
  $content = mt_rand(0, 9999);
  $handle = fopen($filename, 'w');
  fwrite($handle, $content);
  fclose($handle);
  $read_content = '';
  if ($handle = fopen($filename, "rb")) {
    $read_content = fread($handle, filesize($filename));
    fclose($handle);
  }
  unlink($filename);
  $results['mount_rea_write'] = array(
    'title' => t('SANNAS'),
    'value' => t('Write and read works fine'),
    'severity' => _mediamosa_maintenance_status_okerror($content != $read_content),
  );


  $available_bytes = disk_free_space($mount_point);
  $available_mb = floor($available_bytes / 1024 / 1024);
  $results['mount_disk_free'] = array(
    'title' => t('SANNAS'),
    'value' => t('Disk free space: @available Mb', array('@available' => $available_mb)),
    'severity' => ($available_mb <= MEDIAMOSA_MAINTENANCE_STATUS_COMPONENT_SPACE_WARNING ? MEDIAMOSA_MAINTENANCE_STATUS_RESULT_WARNING : ($available_bytes <= 0 ? MEDIAMOSA_MAINTENANCE_STATUS_RESULT_ERROR : MEDIAMOSA_MAINTENANCE_STATUS_RESULT_OK)),
  );

  $statuses = array(
    'component' => array(
      'title' => t('Component status'),
      'results' => $results,
    ),
  );

  if ($with_variable) {
    variable_set('mediamosa_status_component_' . $conf['mediamosa_installation_id'], $statuses);
  }
  return $statuses;
}

/**
 * Implementation of hook_mediamosa_status_collect().
 *
 * @param reset boolean
 * @param with_variable boolean
 *   Use Drupal variables or not
 *
 * @return array
 *   All the statuses in an array
 */
function mediamosa_maintenance_status_component_mediamosa_status_collect($reset = FALSE, $with_variable = TRUE) {
  global $conf;

  if ($reset) {
    return mediamosa_maintenance_status_component_mediamosa_status_generate($with_variable);
  }

  return variable_get('mediamosa_status_component_' . $conf['mediamosa_installation_id'], array());
}
