<?php
// $Id$

/**
 * MediaMosa is Open Source Software to build a Full Featured, Webservice Oriented Media Management and
 * Distribution platform (http://mediamosa.org)
 *
 * Copyright (C) 2009 SURFnet BV (http://www.surfnet.nl) and Kennisnet
 * (http://www.kennisnet.nl)
 *
 * MediaMosa is based on the open source Drupal platform and
 * was originally developed by Madcap BV (http://www.madcap.nl)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, you can find it at:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */

/**
 * Implements the hook_mediamosa_configuration_collect()
 *
 * Hook iterates the configuration form for global settings that are shared
 * on multiple modules into one form; the configuration form.
 */
function mediamosa_configuration_server_mediamosa_configuration_collect() {

  // Get servers.
  $a_servers = mediamosa_server::get_enabled_transcode();
  $a_options = array();

  foreach ($a_servers as $a_server) {
    if (empty($a_server[mediamosa_server_db::SERVER_NAME])) {
      $a_server[mediamosa_server_db::SERVER_NAME] = $a_server[mediamosa_server_db::URI];
    }

    $a_options[$a_server[mediamosa_server_db::URI]] = $a_server[mediamosa_server_db::SERVER_NAME];
  }

  $mediamosa_jobscheduler_uri = variable_get('mediamosa_jobscheduler_uri', NULL);
  if (isset($mediamosa_jobscheduler_uri) && !isset($a_options[$mediamosa_jobscheduler_uri]) && !empty($mediamosa_jobscheduler_uri)) {
    $a_options[$mediamosa_jobscheduler_uri] = t('Current server (not enabled)');
  }

  $form['settings_server'] = array(
    '#type' => 'fieldset',
    '#title' => t('Server settings'),
    '#collapsible' => TRUE,
  );

  if (count($a_options)) {
    $form['settings_server']['mediamosa_jobscheduler_uri'] = array(
      '#type' => 'select',
      '#title' => t('Jobscheduler server'),
      '#description' => t('Select from one of the (enabled) job process servers the server that handles the main job scheduler CRON.'),
      '#required' => TRUE,
      '#options' => $a_options,
      '#default_value' => '',// Set empty, so its filled.
    );
  }
  else {
    $form['settings_server']['mediamosa_jobscheduler_markup'] = array(
      '#markup' => t('No enabled jobscheduler transcoding servers found')
    );
  }
  return $form;
}
