<?php
// $Id$

/**
 * MediaMosa is a Full Featured, Webservice Oriented Media Management and
 * Distribution platform (http://www.vpcore.nl)
 *
 * Copyright (C) 2009 SURFnet BV (http://www.surfnet.nl) and Kennisnet
 * (http://www.kennisnet.nl)
 *
 * MediaMosa is based on the open source Drupal platform and
 * was originally developed by Madcap BV (http://www.madcap.nl)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, you can find it at:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */

/**
 * @file
 * The main maintenance module.
 */
/**
 * Implement hook_menu().
 */

function mediamosa_menu() {
  $items = array();

  // Maintenance / Configuration pages.
  $items['admin/mediamosa'] = array(
    'title' => 'MediaMosa 2',
    'page callback' => 'mediamosa_maintenance_admin_page',
    'access arguments' => array(mediamosa_settings::MEDIAMOSA_PERM_ACCESS_ADMINISTRATION),
    'weight' => -20,
    'file' => 'mediamosa_maintenance.admin.inc',
  );
  $items['admin/mediamosa/mediamosa'] = array(
    'title' => 'Status',
    'access arguments' => array(mediamosa_settings::MEDIAMOSA_PERM_ADMINISTER),
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -10,
    'file' => 'mediamosa_maintenance.admin.inc',
  );
  $items['admin/mediamosa/browse'] = array(
    'title' => 'Browse',
    'access arguments' => array(mediamosa_settings::MEDIAMOSA_PERM_ADMINISTER),
    'type' => MENU_LOCAL_TASK,
    'weight' => 0,
    'file' => 'mediamosa_maintenance.admin.inc',
  );
  $items['admin/mediamosa/configuration'] = array(
    'title' => 'Configuration',
    'description' => 'Change or alter the configuration of MediaMosa.',
    'page callback' => 'mediamosa_configuration_admin_page',
    'access arguments' => array(mediamosa_settings::MEDIAMOSA_PERM_ADMINISTER),
    'type' => MENU_LOCAL_TASK,
    'weight' => 10,
    'file' => 'mediamosa_maintenance.admin.inc',
  );

  return $items;
}
