<?php
// $Id$

/**
 * MediaMosa is a Full Featured, Webservice Oriented Media Management and
 * Distribution platform (http://www.vpcore.nl)
 *
 * Copyright (C) 2009 SURFnet BV (http://www.surfnet.nl) and Kennisnet
 * (http://www.kennisnet.nl)
 *
 * MediaMosa is based on the open source Drupal platform and
 * was originally developed by Madcap BV (http://www.madcap.nl)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, you can find it at:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */

 /**
  * @file
  * De status module.
  * */

/**
 * Trigger status page.
 */
function mediamosa_maintenance_status_cron() {

  $start = time();
  mediamosa::log('mediamosa_maintenance_status_cron started.');

  // Just trigger, it has his own protection on overrun.
  $hostname = variable_get('mediamosa_cron_uri_app', 'localhost');
  $use_localhost = variable_get('mediamosa_cron_uri_app_local', FALSE);

  $a_options = array('do_internal' => TRUE, 'method' => 'HEAD');
  if ($use_localhost) {
    $a_options['headers']['Host'] = $hostname;
    $hostname = 'localhost';
  }

  mediamosa_http::do_head_call('http://' . $hostname  . '/internal/cron/maintenance_status', $a_options);

  // Log it.
  mediamosa::log('mediamosa_maintenance_status_cron ended: @secs', array('@sec' => time() - $start));
}

/**
 * Implements hook_mediamosa_register_rest_call().
 */
function mediamosa_maintenance_status_mediamosa_register_rest_call() {

  $a_rest_calls = array();

  $a_rest_calls['cron/maintenance_status'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_maintenance_status',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::DESCRIPTION => 'Execute the current default unit tests.',
    mediamosa_rest_call::MODULE_NAME => 'mediamosa',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_2_0_0,
    mediamosa_rest_call::ACCESS => mediamosa_rest_call::ACCESS_INTERNAL_ONLY,
  );

  return $a_rest_calls;
}
