<?php
// $Id$

/**
 * Copyright (c) 2008 Madcap BV (http://www.madcap.nl)
 * All rights reserved.
 *
 * Permission is granted for use, copying, modification, distribution,
 * and distribution of modified versions of this work as long as the
 * above copyright notice is included.
 */


/**
 * @file
 * CQL enables developers to create SQL from a standard CQL query.
 */

// CQL Settings
define('CQL_MINIMUM_PHP_VERSION', '5.1.0');

/**
 * All code that are not hooks, or other drupal related functions are
 * not included in our .module file.
 */
require_once('cql.inc');

/**
 * Make sure we meet the requirements needed for our module
 */
function cql_requirements($phase) {
  // Ensure translations don't break at install time
  $t = get_t();

  $a_requirements = array();

  if ($phase == 'runtime') {
    // We require PHP 5 or higher
    if (version_compare(phpversion(), CQL_MINIMUM_PHP_VERSION) < 0) {
      $a_requirements['php'] = array(
        'title' => $t('PHP'),
        'value' => phpversion(),
        'description' => $t('Your PHP installation does not meet the requirements for using the CQL module. CQL requires at least PHP %version.', array('%version' => CQL_MINIMUM_PHP_VERSION)),
        'severity' => REQUIREMENT_ERROR
      );
    }
  }

  return $a_requirements;
}
