<?php
// $Id$

/**
 * MediaMosa is a Full Featured, Webservice Oriented Media Management and
 * Distribution platform (http://www.vpcore.nl)
 *
 * Copyright (C) 2009 SURFnet BV (http://www.surfnet.nl) and Kennisnet
 * (http://www.kennisnet.nl)
 *
 * MediaMosa is based on the open source Drupal platform and
 * was originally developed by Madcap BV (http://www.madcap.nl)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, you can find it at:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */


/**
 * @file
 * CQL enables developers to create SQL from a standard CQL query.
 */

// CQL Settings
define('MEDIAMOSA_CQL_MINIMUM_PHP_VERSION', '5.1.0');

/**
 * Make sure we meet the requirements needed for our module
 */
function mediamosa_cql_requirements($phase) {
  // Ensure translations don't break at install time
  $t = get_t();

  $a_requirements = array();

  if ($phase == 'runtime') {
    // We require PHP 5 or higher
    if (version_compare(phpversion(), MEDIAMOSA_CQL_MINIMUM_PHP_VERSION) < 0) {
      $a_requirements['php'] = array(
        'title' => $t('PHP'),
        'value' => phpversion(),
        'description' => $t('Your PHP installation does not meet the requirements for using the MediaMosa CQL module. MediaMosa CQL requires at least PHP %version.', array('%version' => MEDIAMOSA_CQL_MINIMUM_PHP_VERSION)),
        'severity' => REQUIREMENT_ERROR
      );
    }
  }

  return $a_requirements;
}
