<?php
// $Id$

/**
 * MediaMosa is Open Source Software to build a Full Featured, Webservice Oriented Media Management and
 * Distribution platform (http://mediamosa.org)
 *
 * Copyright (C) 2011 SURFnet BV (http://www.surfnet.nl) and Kennisnet
 * (http://www.kennisnet.nl)
 *
 * MediaMosa is based on the open source Drupal platform and
 * was originally developed by Madcap BV (http://www.madcap.nl)
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, you can find it at:
 * http://www.gnu.org/licenses/old-licenses/gpl-2.0.html
 */

/**
 * @file
 * Tiff tool module.
 */

// Constants.
/**
 * Mime type: application/pdf
 */
define('MEDIAMOSA_TOOL_TIFF_MIME_TYPE_TIFF', 'image/tiff');

/**
 * Implements hook_mediamosa_tool_analyse().
 */
function mediamosa_tool_tiff_mediamosa_tool_analyse($mime_type) {
  $is_found = FALSE;

  switch ($mime_type) {
    case MEDIAMOSA_TOOL_TIFF_MIME_TYPE_TIFF:
      $is_found = TRUE;
      break;
  }

  return ($is_found ? '/internal/job/$job_id/exec/tiff' : FALSE);
}

/**
 * Implements hook_mediamosa_register_rest_call().
 */
function mediamosa_tool_tiff_mediamosa_register_rest_call() {

  $rest_calls = array();

  $rest_calls['job/$job_id/exec/tiff'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::CLASS_NAME => 'mediamosa_rest_call_job_exec_tiff',
    mediamosa_rest_call::STATUS => mediamosa_rest_call::STATUS_ACTIVE,
    mediamosa_rest_call::MODULE_NAME => 'mediamosa_tool_tiff',
    mediamosa_rest_call::VERSION => mediamosa_version::MEDIAMOSA_VERSION_2_3_0,
    mediamosa_rest_call::ACCESS => mediamosa_rest_call::ACCESS_INTERNAL_ONLY,
    mediamosa_rest_call::NO_USER_ABORT => TRUE,
  );

  return $rest_calls;
}

/**
 * Implements hook_mediamosa_register_rest_call_doc().
 */
function mediamosa_tool_tiff_mediamosa_register_rest_call_doc() {

  $rest_calls = array();

  $rest_calls['job/$job_id/exec/tiff'][mediamosa_rest_call::METHOD_GET] = array(
    mediamosa_rest_call::TITLE => 'Start transcoding Tiff.',
    mediamosa_rest_call::DESCRIPTION => 'Start transcoding Tiff.',
    mediamosa_rest_call::EXAMPLE_REQUEST => '',
    mediamosa_rest_call::RESPONSE_FIELDS => array(),
    mediamosa_rest_call::EXAMPLE_RESPONSE => '',
  );

  return $rest_calls;
}
